"""question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {
        "text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
        "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]"""

question_data = [{"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "The capital of the US State Ohio is the city of Chillicothe.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard",
                  "category": "Science: Computers",
                  "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard",
                  "category": "Entertainment: Board Games",
                  "question": "The board game Go has more possible legal positions than the number of atoms in the visible universe.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Vehicles",
                  "question": "The term &quot;GTO&quot; was originated by Ferrari?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Science: Computers",
                  "question": "The logo for Snapchat is a Bell.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Video Games",
                  "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Geography",
                  "question": "The two largest ethnic groups of Belgium are Flemish and Walloon. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Japanese Anime &amp; Manga",
                  "question": "Studio Ghibli is a Japanese animation studio responsible for the films &quot;Wolf Children&quot; and &quot;The Boy and the Beast&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                  "question": "Ferrari has never made a V10 engine for any of its cars.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Television",
                  "question": "Bob Ross was a US Air Force pilot.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Video Games",
                  "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Music",
                  "question": "Scatman John&#039;s real name was John Paul Larkin.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Computers",
                  "question": "Android versions are named in alphabetical order.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard",
                  "category": "Science: Mathematics",
                  "question": "If you could fold a piece of paper in half 50 times, its&#039; thickness will be 3\/4th the distance from the Earth to the Sun.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Politics",
                  "question": "The S in Harry S. Truman stands for &quot;Samuel&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Board Games",
                  "question": "&quot;Rich Uncle Pennybags&quot; from the board game &quot;Monopoly&quot; wears a monocle.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Television",
                  "question": "In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "The Hundred Years&#039; War was fought for more than a hundred years.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Geography",
                  "question": "New Haven is the capital city of the state of Connecticut in the United States.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Video Games",
                  "question": "Codemasters is the developer of the Gran Turismo series.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Music",
                  "question": "Daft Punk originated in France.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Science: Computers",
                  "question": "Linus Torvalds created Linux and Git.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Japanese Anime &amp; Manga",
                  "question": "The animated film &quot;Spirited Away&quot; won the Academy Award for Best Animated Feature at the 75th Academy Awards in 2003.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "Kissing someone for one minute burns about 2 calories.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Mathematics",
                  "question": "The set of all algebraic numbers is countable.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard", "category": "History",
                  "question": "The USS Missouri (BB-63) last served in the Korean War.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Video Games",
                  "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "General Knowledge",
                  "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science &amp; Nature",
                  "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard",
                  "category": "General Knowledge",
                  "question": "NCIS stands for &quot;Navy Corps Investigative Service&quot;",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "General Knowledge",
                  "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Animals",
                  "question": "Rabbits can&#039;t vomit.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                  "question": "The majority of Subaru vehicles are made in China.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Animals",
                  "question": "A caterpillar has more muscles than humans do.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Video Games",
                  "question": "The main playable character of the 2015 RPG &quot;Undertale&quot; is a monster.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "The Fiat Multipla is a drivable car in &quot;Forza Horizon 3&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "The longest place named in the United States is Lake Chargoggagoggmanchauggagoggchaubunagungamaugg, located near Webster, MA.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Television",
                  "question": "In &quot;Star Trek&quot;, Klingons are aliens.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Sports",
                  "question": "There are a total of 20 races in Formula One 2016 season.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Film",
                  "question": "Sean Connery wasn&#039;t in &quot;Indiana Jones and the Kingdom of the Crystal Skull&quot; because he found retirement too enjoyable.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Mythology",
                  "question": "In Norse mythology, Thor once dressed as a woman.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Video Games",
                  "question": "Donkey Kong was originally set to be a Popeye arcade game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Video Games",
                  "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "General Knowledge",
                  "question": "The Lego Group was founded in 1932.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Film",
                  "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "In Portal, the Companion Cube&#039;s ARE sentient.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Books",
                  "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel &quot;The Lord of The Rings&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Sports",
                  "question": "The Olympics tennis court is a giant green screen.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "hard",
                  "category": "Entertainment: Music",
                  "question": "The band STRFKR was also briefly known as Pyramiddd.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
